name: MCP Grocy API
version: "1.4.7"
slug: mcp_grocy_api
description: Home Assistant addon for MCP server that communicates with Grocy REST API
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
panel_icon: mdi:cart
options:
  grocy_base_url: https://your-grocy-instance.com
  grocy_api_key: your_grocy_api_key_here
  enable_ssl_verify: true
  rest_response_size_limit: 10000
  enable_http_server: true
  http_server_port: 8080
schema:
  grocy_base_url: url
  grocy_api_key: password
  enable_ssl_verify: bool?
  rest_response_size_limit: int(1000,)?
  enable_http_server: bool
  http_server_port: port
ports:
  "8080/tcp": "8080"
ports_description:
  "8080/tcp": "Default HTTP port"
image: "ghcr.io/saya6k/hassio-addons/{arch}-addon-mcp-grocy-api" # Version will be appended by build
