name: MCP Grocy API
version: "1.1.0"
slug: mcp_grocy_api
description: A Home Assistant addon for MCP Grocy API.
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
panel_icon: mdi:cart
options: {}
schema: {}