name: Debug Workflow Triggers

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  debug:
    name: Debug Tag Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Debug Information
        run: |
          echo "=== Debug Information ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "========================"
