name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure Git
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
      
      - name: Install dependencies
        run: npm ci
        
      - name: Install semantic-release dependencies
        run: npm install --no-save @semantic-release/git @semantic-release/changelog semantic-release

      - name: Generate release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}