name: Trigger Hass.io Addon Submodule Update on Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0, v1.2.3, etc.

permissions:
  contents: read  # Need to read repository contents
  actions: write  # Need to trigger other workflows

jobs:
  call_publish_hassio_addon:
    name: Call Publish Hass.io Addon Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug tag information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          
      - name: Get version from tag
        id: get_version
        run: |
          TAG_NAME="${{ github.ref_name }}"
          # Remove 'v' prefix, as publish-hassio-addon.yml expects the pure version number
          VERSION_NUMBER="${TAG_NAME#v}"
          echo "Tag received: $TAG_NAME"
          echo "Extracted version for submodule update: $VERSION_NUMBER"
          echo "release_version=$VERSION_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Call Publish Hass.io Addon Workflow
        uses: ./.github/workflows/publish-hassio-addon.yml
        with:
          release_version: ${{ steps.get_version.outputs.release_version }}
        secrets:
          HASSIO_ADDONS_TOKEN: ${{ secrets.HASSIO_ADDONS_TOKEN }}
          
      - name: Workflow completion
        run: |
          echo "=== Trigger Workflow Completed ==="
          echo "Successfully triggered submodule update for version: ${{ steps.get_version.outputs.release_version }}"
          echo "================================"
