name: Validate Configuration

on:
  push:
    branches: [main, dev]
    paths:
      - '.releaserc.json'
      - '.release-dev.json'
      - 'scripts/verify-release-config.js'
  pull_request:
    branches: [main, dev]
    paths:
      - '.releaserc.json'
      - '.release-dev.json'
      - 'scripts/verify-release-config.js'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  validate-config:
    name: Validate Release Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Release Configuration Validation
        run: |
          echo "Verifying release configuration files..."
          npm run verify-release-config
